import Header from '@/components/Header';
import { ReduxProviderWrapper } from '@/components/ReduxProviderWrapper';
import type { Metadata } from 'next';
import { Dosis, Geist, Geist_Mono, Nunito_Sans } from 'next/font/google';
import '@/app/globals.css';

const dosisSans = Dosis({
  variable: '--font-dosis-sans',
  subsets: ['latin'],
});

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${dosisSans.variable} ${nunitoSans.variable} antialiased`}>
        <Header />
        <ReduxProviderWrapper>{children}</ReduxProviderWrapper>
      </body>
    </html>
  );
}
